### ISSUE TITLE
[Question] Migration issue

### ISSUE THREAD

**Issue by scheung38** [tedcrimson/authentication_repository#1]
flutter pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

if this is the only one that is not null safe, I should not migrate?

![Screenshot 2021-03-25 at 20 29 52](https://user-images.githubusercontent.com/1273014/112539409-e02d0100-8da8-11eb-9e3c-763b7684a180.png)

**Comment by tedcrimson** [comment]
Thanks for the issue. Now it is up to date.
